moveis = ['mesa', 'cadeira', 'sofa', 'criado']
print(moveis)
print("1. Acessando o primeiro item da lista (com índice 0):",moveis[0])
print("2. Acessando o último item da  lista (com índice -1):",moveis[-1])
print("3. Acessando o segundo item da lista e com letra maiúscula: ", moveis[1].title())
moveis.append('fogao')
print("4. Acrescentando itens no final da lista: " ,moveis)
moveis.insert(0, 'geladeira')
print("5. Inserindo elementos em uma lista: ", moveis)
del moveis[0]
print("6. Deletando itens em uma lista de forma definitiva: ", moveis)
print("7. Removendo e visualizando o item removido: ",moveis.pop(0))
moveis.remove('sofa')
print("8. Removendo itens de acordo  com o valor: ", moveis)
moveis.sort()
print("9. Ordenando uma lista: ", moveis)
moveis.sort(reverse=True)
print("9. Ordenando uma lista de forma reversa: ", moveis)
print("Usando o sorted: ", sorted(moveis))
print("10. Descobrindo o numero de itens  da lista: ", len(moveis))